### ISSUE TITLE
Can not get the performence

### ISSUE THREAD

**Issue by trillionpowers** [tyshiwo/DRRN_CVPR17#6]
I am a reader from shanghai, I had used your caffemodel to test the 'set5', 'set14', 'BSDS100' and 'Urban100'. For 'set5' , 'set14' and 'Urban100', I can get the performence. But for 'BSDS100', I can not get the performence. 
I do not know how to handle this. Maybe you can give me the best model.
Thank you.

**Comment by tyshiwo** [comment]
Hi, I don't know exactly the reason for your performance on BSDS100, but I guess maybe you used the incorrect images for BSDS100. Here is a link for the test sets: http://vllab1.ucmerced.edu/~wlai24/LapSRN/.

By the way, since I start to work now, I do not have time to push DRRN to achieve better performance. You may have interests on our recent work MemNet: https://github.com/tyshiwo/MemNet, which achieves better results on benchmarks compared to DRRN.

**Comment by trillionpowers** [comment]
I think I download BSDS100 dataset in many different sites include the site you gived me. But it still did not get the performence mentioned in your paper(PSNR: 32.05). And I retrained your network, saved about 30 caffemodels. But the best performence for PSNR is 27.58.

**Comment by trillionpowers** [comment]
Maybe you give me a link that stored your own results about BSDS100.
Thank you.

**Comment by tyshiwo** [comment]
Hi, you can find our results here: https://drive.google.com/file/d/0BwcCYzjI8Z4qVkpnNUNGYmQ2NUE/view?usp=sharing

We got exactly the same performance as shown in the paper using the DRRN_B1U25 model. Hope that helps you.

**Comment by trillionpowers** [comment]
Thank you. But I think I also need results of 'x3' and 'x4'.
Please give the link.
Thanks a lot

**Comment by trillionpowers** [comment]
Thank you. But I think I also need results of 'x3' and 'x4'.
Please give me the link.
Thanks a lot

**Comment by tyshiwo** [comment]
Hi, you can find the images of BSDS100 here: 
https://drive.google.com/file/d/0BwcCYzjI8Z4qOXpjbEJqUGR5TnM/view?usp=sharing

You may use test_DRRN_B1U25.m to get the results of 'x3' and 'x4'.
